// This file is auto-generated by the build process. Do not edit this file directly.
// If you want to update the content, please edit the source file at src/pages/humans.txt and rebuild the project.

import type { APIRoute } from "astro";

const baseHumansTxt = `
/*         ██                                                                                             */
/*      ████                                        █                         ██                          */
/*     ██                                          ██                         ██                          */
/*     ███         ██                     ███      ██      ██                ██   ██      ███             */
/*       ███    ███ ███     ██  ██  ████  ███   █████   ███ ███     ████     ██ ███      ██ ██   ██ ███   */
/*         ██  ██   ███    █████████████  ██████  ███  ██   ███    ██       █████       █████    ████     */
/*         ██  █████████   ████ ███  ██   ██      ██   ██ ██████  ██     ███████████     ██      ███      */
/*   █   ███   ████    ██ ███   ██   █   ██       ██   ████   ███ ████████   ██     █    ██████ ██        */
/*    ███                                         ██                                                      */

/* TEAM */
	Developer: SamHacker
	GitHub: @510208
	Website: https://510208.github.io
	Website: https://samhacker.xyz
	Twitter: @xux510208
	Threads: @samhacker.xyz
	From: Taichung, Taiwan

/* THANKS */
	Thanks to all the open source contributors and the communities that make the web a better place!
	
	Name: Nelson Lai
	Website: https://nelsonlai.dev
	Name: 木白
	Website: https://s24egao.com/
	Name: Zhenyuan 工作室
	Website: https://zhenyuan.dev/
	Name: SamHacker Dev
	Website: https://samhacker.xyz/

/* SITE */
	Last update: ${new Date().toISOString().split("T")[0].replaceAll("-", "/")}
	Language: Chinese (Traditional)
	Framework: Astro
	UI Framework: React
	Component Library: shadcn/ui
	CSS Framework: Tailwind CSS
	Animation Library: GSAP
	Hosting: GitHub Pages
	Source code: https://github.com/510208/510208.github.io
	IDE: Microsoft Visual Studio Code
`;

export const GET: APIRoute = ({ site }) => {
  return new Response(baseHumansTxt);
};
